### ISSUE TITLE
No effect on H170M-D3H

### ISSUE THREAD

**Issue by Cysioland** [xdarklight/gigabyte_ambientled_ctrl#1]
GPIO works, all well, values get written, but the trace stays the color and lighting it was before.

**`dmesg` line:** `[   53.836486] gpio_it87: Found Chip IT8628 rev 2. 64 GPIO lines starting at 0a00h` 
**Distro:** Antergos Linux 
**Kernel:** 4.7.2-1-ARCH

**Comment by xdarklight** [comment]
Maybe the LEDs are connected to a different GPIO on your board.
Could you please try the following script (which is derived from https://wiki.openwrt.org/doc/hardware/port.gpio#script_static):

```
#!/bin/bash
GPIOBASE=`cat /sys/class/gpio/gpiochip*/base | head -n1`
GPIOmin=`expr $1 + $GPIOBASE`
GPIOmax=`expr $2 + $GPIOBASE`

cd /sys/class/gpio

for i in `seq $GPIOmin $GPIOmax`; do
    echo $i > export
done

for gpio in `ls -1 | grep it87_gp`; do
    echo "[$gpio] Trying value $3"
    echo out > $gpio/direction
    echo $3 > $gpio/value
    sleep 2s
done
```

Then run it like this (as root) to test all 64 GPIOs:

```
sh <path to>/testscript.sh 0 64 0
```

Watch your LEDs while the script is running.
Press CTRL+C once the LEDs are turning off.

**Comment by Cysioland** [comment]
Went off (and later on when substituted the last parameter to 1) on it87_gp26

**Comment by xdarklight** [comment]
sorry for the huge delay - I've been very busy with other things.
I guess a bit of refactoring of my scripts is needed, based on ``/sys/class/dmi/id/board_name`` we probably have to choose different GPIOs.

I'll try to have a look at the Gigabyte tool again in the next few days to see how Gigabyte itself does this detection.

**Comment by Cysioland** [comment]
No problem, after all, you've been doing this for free, in your spare time.
And I'm glad I can supply my testing help.

**Comment by xdarklight** [comment]
@Cysioland could you please try this branch and give feedback whether it works for you or not: https://github.com/xdarklight/gigabyte_ambientled_ctrl/tree/feature/h170m-d3h-v1

**Comment by Cysioland** [comment]
```
./gpio_it87.sh: line 13: echo: write error: Invalid argument
./gpio_it87.sh: line 16: /sys/class/gpio/it87_gp82/direction: No such file or directory
./gpio_it87.sh: line 17: /sys/class/gpio/it87_gp82/value: No such file or directory
./gpio_it87.sh: line 13: echo: write error: Invalid argument
./gpio_it87.sh: line 16: /sys/class/gpio/it87_gp83/direction: No such file or directory
./gpio_it87.sh: line 17: /sys/class/gpio/it87_gp83/value: No such file or directory
Turning audio LED off...
```

Of course, no effect

**Comment by Cysioland** [comment]
And in `dmesg`:

```
[ 3792.052600] export_store: invalid GPIO 506
[ 3792.053511] export_store: invalid GPIO 507
```

**Comment by xdarklight** [comment]
could you please also provide the output of ``cat /sys/kernel/debug/gpio | grep gpio_it87``?
on my board this gives "gpiochip0: GPIOs 448-511, gpio_it87:" hence the assumptions in the script

**Comment by Cysioland** [comment]
It outputs nothing

**Comment by xdarklight** [comment]
is the gpio-it87 module loaded?
what does ``ls /sys/class/gpio`` give you?

**Comment by Cysioland** [comment]
export  unexport

**Comment by Cysioland** [comment]
Meanwhile I updated kernel to 4.8

**Comment by Cysioland** [comment]
Okay, module loaded, and now there are no errors, but it simply doesn't change anything

**Comment by xdarklight** [comment]
OK, after you ran the script from my branch, could you please provide the output of:
```cat /sys/kernel/debug/gpio``` and ```ls /sys/class/gpio```?

**Comment by Cysioland** [comment]
First one is empty, second one is `export unexport`

**Comment by xdarklight** [comment]
can you please make sure that the gpio-it87 driver is loaded?
without this driver my script cannot work

you can run: ```modprobe gpio-it87```
and verify that it has been loaded by running: ```lsmod | grep it87 | grep gpio```

**Comment by Cysioland** [comment]
`/sys/kernel/debug/gpio`: https://gist.github.com/e22dfe3315c748113bb78b1a1a899675  
`/sys/class/gpio`: https://gist.github.com/23451d947c96333d9430450c0db00c20

**Comment by xdarklight** [comment]
that looks good so far

can you please share the output of ```cat /sys/class/dmi/id/board_name```?

if you use the latest version of this script from the master branch, what happens if you run ```./audio_led_mode.sh on``` or ```./audio_led_mode.sh off```?

**Comment by Cysioland** [comment]
Sure, https://gist.github.com/cfd4c826aa6c98f37ca36b87ddb4b95e

It doesn't turn off, when I run it.

**Comment by xdarklight** [comment]
can you please try again with 5e594c0?

if it still doesn't work then I'm interested in the output of ```bash -x audio_led_mode.sh on```

thanks for your patience!

**Comment by Cysioland** [comment]
Works now, correctly turns the light off and on. Now only to get a case that'll benefit from this…

**Comment by xdarklight** [comment]
great - congratulations!
