### ISSUE TITLE
Bad substitution

### ISSUE THREAD

**Issue by PenguinPaul** [xdarklight/gigabyte_ambientled_ctrl#3]
When running the script, this error results:

`./audio_led_mode.sh: 29: ./audio_led_mode.sh: Bad substitution`

This can be amended my changing the shebang from `#!/bin/sh` to `#!/bin/bash`.  By default on some distributions, `#!/bin/sh` points to dash, which is not compatible with this script.  Changing the shell to bash fixes the issue.

**Comment by xdarklight** [comment]
thanks for reporting!
