### ISSUE TITLE
[WORKS] GA-Z170X-UD5 TH

### ISSUE THREAD

**Issue by ChrisBdk** [xdarklight/gigabyte_ambientled_ctrl#5]
Just wanted to inform you, that it runs on GA-Z170X-UD5 TH mobos...

// Cheers

**Comment by xdarklight** [comment]
Hi @ChrisBlow,

thanks for letting me know!
Could you do me a small favor and paste the result of: ```cat /sys/class/dmi/id/board_name```
I'll update README.md afterwards

Regards,
Martin

**Comment by ChrisBdk** [comment]
Here you go:
Z170X-UD5 TH-CF


The sound function is'n reacting, but the board supports it....
Venlig Hilsen / Best regards


Bjørn Christiansen
ChrisB

Bredstedgade 6 st th
DK5000 Odense C
Denmark
LTE :+45 2266 6693 <tel:+45 2266 6693>
Email :<bc@chrisb.dk>
Web / Facebook :<http://chrisb.dk/>
Twitter : chrisb_dk
LinkedIn / Instagram / Pinterest : chrisbdk
Support or donate via Paypal : <http://paypal.me/ChrisBdk>

**Comment by xdarklight** [comment]
I've updated the README.md in 38fdfb497d9e1c837ae133ab77d6b69d8a4ae6d3

Does the audio function work when you enable it in EFI, leave it untouched in Linux and then play some music?

**Comment by ChrisBdk** [comment]
Yes, it beats / pulses to the audio..
and just noticed that PWR_LED ( pin:-17-19 +15 ) on the Front Panel Header is outputting the same.. :)

Venlig Hilsen / Best regards


Bjørn Christiansen
ChrisB

Bredstedgade 6 st th
DK5000 Odense C
Denmark
LTE :+45 2266 6693 <tel:+45 2266 6693>
Email :<bc@chrisb.dk>
Web / Facebook :<http://chrisb.dk/>
Twitter : chrisb_dk
LinkedIn / Instagram / Pinterest : chrisbdk
Support or donate via Paypal : <http://paypal.me/ChrisBdk>

**Comment by xdarklight** [comment]
OK, so this means my script breaks it?
I don't use on-board audio, but I can enable it and test once I have a bit more time.

**Comment by ChrisBdk** [comment]
No..
Now thats funny..

Your script makes it pulse in and out, while it reacts to the music?!?!

In EFI I can set it to beat mode, and it work..
Venlig Hilsen / Best regards


Bjørn Christiansen
ChrisB

Bredstedgade 6 st th
DK5000 Odense C
Denmark
LTE :+45 2266 6693 <tel:+45 2266 6693>
Email :<bc@chrisb.dk>
Web / Facebook :<http://chrisb.dk/>
Twitter : chrisb_dk
LinkedIn / Instagram / Pinterest : chrisbdk
Support or donate via Paypal : <http://paypal.me/ChrisBdk>

**Comment by xdarklight** [comment]
closing as I am not longer actively maintaining this project
