### ISSUE TITLE
Support for z270n-gaming5

### ISSUE THREAD

**Issue by pbaj** [xdarklight/gigabyte_ambientled_ctrl#6]
Want support for Gigabyte Z270N-Gaming5. 

Tried but it says:

grep: /sys/class/gpio/gpiochip*/label: No such file or directory
./gpio_it87.sh: line 22: could not find gpio_it87 GPIO entry
make sure the gpio_it87 driver is supported by your kernel and loaded: syntax error in expression (error token is "not find gpio_it87 GPIO entry
make sure the gpio_it87 driver is supported by your kernel and loaded")

**Comment by xdarklight** [comment]
these scripts only work after the ``gpio_it87`` module has been loaded
not all distributions are shipping that module

what do you get when running ```lsmod | grep gpio_it87```?

**Comment by ijash** [comment]
is there a simple tutorial to install gpio_it87? i am using linux mint. and nothing found on lsmod. please help

**Comment by xdarklight** [comment]
> i am using linux mint. and nothing found on lsmod.

can you please show the output of ```$ zcat /proc/config.gz | grep GPIO_IT87```.
I don't know if Linux Mint enables the driver in the kernel configuration -> this project doesn't work if that driver isn't enabled.

**Comment by ijash** [comment]
> > i am using linux mint. and nothing found on lsmod.
> 
> can you please show the output of `$ zcat /proc/config.gz | grep GPIO_IT87`.
> I don't know if Linux Mint enables the driver in the kernel configuration -> this project doesn't work if that driver isn't enabled.

it returned: 
`gzip: /proc/config.gz: No such file or directory`
I am using `gigabyte z270x ud3` is it compatible?
so, for linux mint is a dead end? which distro should be compatible for this?
thanks in advance.

**Comment by xdarklight** [comment]
> I am using gigabyte z270x ud3 is it compatible?

your board is not **yet** compatible we can make it compatible (assuming it uses a similar hardware setup as any of the already supported boards)

> so, for linux mint is a dead end?

no, Linux Mint is not a dead end. please open a feature request with your distro maintainer asking to enable ```CONFIG_GPIO_IT87=m``` (they will probably ask why: please link them to this project).

**Comment by ijash** [comment]
> > I am using gigabyte z270x ud3 is it compatible?
> 
> your board is not **yet** compatible we can make it compatible (assuming it uses a similar hardware setup as any of the already supported boards)
> 
> > so, for linux mint is a dead end?
> 
> no, Linux Mint is not a dead end. please open a feature request with your distro maintainer asking to enable `CONFIG_GPIO_IT87=m` (they will probably ask why: please link them to this project).

Thank you very much!

**Comment by ijash** [comment]
hi, back again, i was told to check with
 ```grep CONFIG_GPIO_IT87 /boot/config-4.15.0-43-generic ```
and found. then:
```modinfo gpio-it87```
and it shows:
```
filename:       /lib/modules/4.15.0-43-generic/kernel/drivers/gpio/gpio-it87.ko
license:        GPL
description:    GPIO interface for IT87xx Super I/O chips
author:         Diego Elio PettenÃ² <flameeyes@flameeyes.eu>
srcversion:     37631A872228DD92D8E4308
depends:        
retpoline:      Y
intree:         Y
name:           gpio_it87
vermagic:       4.15.0-43-generic SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4

```
does that mean it's enabled in linux mint? if so, how can i continue? please advise.

**Comment by xdarklight** [comment]
> does that mean it's enabled in linux mint? if so, how can i continue? please advise.

what happens if you run ``modprobe gpio_it87``?

can you please also show the output of ``dmesg | grep -i it87``

**Comment by ijash** [comment]
Hi, @xdarklight 

`sudo modprobe gpio_it87`

 returned: 
`modprobe: ERROR: could not insert 'gpio_it87': No such device
`
and 
`dmesg | grep -i it87`
 returned:
`[ 4969.196072] gpio_it87: Unknown Chip found, Chip 8686 Revision 2`

**Comment by xdarklight** [comment]
> Chip 8686 Revision 2

that chip is not supported by the gpio_it87 driver yet.
I'll need to investigate and check the Gigabyte LED tool for Windows before I can tell you more. stay tuned

**Comment by mirh** [comment]
Likely: https://github.com/frankcrawford/it87

**Comment by xdarklight** [comment]
closing as I am not longer actively maintaining this project
