### ISSUE TITLE
Support for H410M S2H 

### ISSUE THREAD

**Issue by NextWork123** [xdarklight/gigabyte_ambientled_ctrl#7]
Hi Guys, i wanted to ask if is possible to have ambient led working on H410M S2H for now i'm running Arch Linux with a custom kernel CK. My motherboard have this chip: `[  554.735528] gpio_it87: Unknown Chip found, Chip 8688 Revision 1` and i think isn't supporting by the gpio_it87 driver. I hope you can help me :+1: 

Best Regards,
NextWorks

**Comment by xdarklight** [comment]
to answer this question one would need to know:
- how that board integrates the LED configuration
  - on mine turning the LEDs on/off is simple: we "just" need to toggle one GPIO
  - however, there are newer boards where the ITE chip is using a more advanced firmware and communication is more complex
- depending on the answer to the first question:
  - either we would need to find out how to make gpio_it87 work with the "ITE8688" chip
  - or find a way for the "more advanced" communication

so my answer is:
possible: yes (as most things in life)
realistic: no, unless you implement it yourself

**Comment by xdarklight** [comment]
closing as I am not longer actively maintaining this project
